### ISSUE TITLE
How are the autocompleted options for a component chosen?

### ISSUE THREAD

**Issue by aabmass** [dash0hq/otelbin#162]
First off thanks for working on this, it's pretty cool.

I'm wondering how the autocompleted options for a component are chosen. When I type `googlecloud<TAB>` in the exporters section, it automatically adds the following config keys:

```yaml
  googlecloud:
    project: 
    user_agent: opentelemetry-collector-contrib {{version}}
    destination_project_quota: false
    timeout: "12s"
```

All but `project` are not options that users would normally want to tweak. It seems like the defaults come maybe come from the mapconfig default struct tag? I would guess that options with a default are usually the least relevant to users.
