### ISSUE TITLE
Improve UX for Kubernetes CRDs

### ISSUE THREAD

**Issue by mmanciop** [dash0hq/otelbin#210]
With #207, OTelBin is stripping the CR envelope, but the experience feels surprising and not understandable, as the content you pasted is not what you copied. Instead, we should keep the CR envelop, and commented it out. For example, consider the [following CR](https://github.com/open-telemetry/opentelemetry-operator#getting-started) from the OpenTelemetry operator repository:

```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug]
```

In OTelBin, the content of the edit pane should be:

```yaml
# apiVersion: opentelemetry.io/v1alpha1
# kind: OpenTelemetryCollector
# metadata:
#  name: simplest
# spec:
#  config: |
receivers:
  otlp:
    protocols:
      grpc:
      http:
processors:
  memory_limiter:
    check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
    batch:
      send_batch_size: 10000
      timeout: 10s

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug]
```

Notice that, in the above:
1. All CR-related YAML is commented out with an additional `# ` string at the the beginning of the line. This should apply also to lines that already start with `#` so that VS Code or similar IDEs can strip it away again easily.
2. The indentation of the actual configuration is adjusted.

This, coupled with #194, would lead to a smooth experience using OTelBin with the OpenTelemetry operator, as the commented-out YAML keeps the namespace, name, label and other metadata the end user will need to be able to directly patch their resources.
