### ISSUE TITLE
Detect cycles in connectors when using browser-only validation

### ISSUE THREAD

**Issue by mmanciop** [dash0hq/otelbin#258]
The browser-only validation should detect cycles like:

```yaml
receivers:
  otlp:
exporters:
  otlp:
    endpoint: https://foo.bar
connectors:
  count/count_1:
  count/count_2:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [count/count_1, otlp]
    metrics:
      receivers: [count/count_1]
      exporters: [count/count_2]
    metrics/count_the_counts:
      receivers: [count/count_2]
      exporters: [count/count_1]
```
