### ISSUE TITLE
Improve error reporting for distro validation

### ISSUE THREAD

**Issue by mmanciop** [dash0hq/otelbin#259]
When parsing a configuration with cycles in the connectors, the actual error is not visible:

<img width="663" alt="Screenshot 2023-12-12 at 12 40 56" src="https://github.com/dash0hq/otelbin/assets/14020598/63179209-aa02-431d-ac13-71cba05fd51c">

Repro:

```yaml
receivers:
  otlp:
exporters:
  otlp:
    endpoint: https://foo.bar
connectors:
  count/count_1:
  count/count_2:
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [count/count_1, otlp]
    metrics:
      receivers: [count/count_1]
      exporters: [count/count_2]
    metrics/count_the_counts:
      receivers: [count/count_2]
      exporters: [count/count_1]
```
