### ISSUE TITLE
OTelBin crashes when the name of a pipeline component is a number

### ISSUE THREAD

**Issue by bripkens** [dash0hq/otelbin#273]
# Why
Define a pipeline such as this crashes OTelBin:

```yaml
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, 123]
      exporters: [otlp]
```

This is because the YAML parser turns `123` into a number. Before we execute any kind of logic on the processor names, we need to ensure that they are strings.

The collector itself would likely also reject such a configuration, but OTelBin should not fatally error out.

# What

 - [ ] Make sure OTelBin doesn't crash on this
 - [ ] Make sure the social image generation doesn't crash on this
 - [ ] Write test cases for both scenarios
