### ISSUE TITLE
in-browser validation does not validate OTTL

### ISSUE THREAD

**Issue by bripkens** [dash0hq/otelbin#386]
The current in-browser validation only validates JSON schema compliance. However, this fully skips any validation of OTTL expressions. Consequently, it doesn't find errors like this (trailing `'`'):

```yaml
processors:
  batch: {}
  filter/metricDenylist:
    error_mode: ignore
    metrics:
      metric:
        - type == METRIC_DATA_TYPE_NONE'
```
