### ISSUE TITLE
Add lint warning for unused extensions

### ISSUE THREAD

**Issue by garysassano** [dash0hq/otelbin#411]
Currently, when an extension is defined but never used, there is no clear warning. To improve usability, the warning message could follow the style of ESLint's unused variable warnings.

#### Example Configuration
```yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: otelcol:4317

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
```

#### Expected Output
```
warning: 'health_check' is defined but never used. (unused-extension)
```

This would make it easier to identify unused extensions. I had an issue where I had lots of extensions and I forgot to include one in the `service` section. I spent half an hour debugging an issue that could have been resolved immediately.
